apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: myapp-apps
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/REPLACE_EXTERNAL_SECRETS_ROLE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: myapp-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/REPLACE_EXTERNAL_SECRETS_ROLE
