apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-apps

resources:
  - sql-secrets.example.yaml
  - sql-pvc.yaml
  - sql-service.yaml
  - statefulset-mssql.yaml
  - job-bootstrap-databases.yaml
  - backup-cronjob.yaml
