apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: myapp-apps
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/part-of: myapp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sqlserver
  ports:
    - name: tds
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-headless
  namespace: myapp-apps
  labels:
    app.kubernetes.io/name: sqlserver
    app.kubernetes.io/part-of: myapp
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: sqlserver
  ports:
    - name: tds
      port: 1433
      targetPort: 1433
