<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApp.Agentic.Domain\MyApp.Agentic.Domain.csproj" />
    <ProjectReference Include="..\MyApp.Agentic.Application.Contracts\MyApp.Agentic.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyApp.Agentic.Infrastructure\MyApp.Agentic.Infrastructure.csproj" />
    <ProjectReference Include="..\..\MyApp.Shared\MyApp.Shared.Domain\MyApp.Shared.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.4.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.4.0" />
    <PackageReference Include="OpenAI" Version="2.10.0" />
  </ItemGroup>

</Project>