<Project Sdk="Aspire.AppHost.Sdk/13.2.4">
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>6dd05225-6440-435e-80fe-b6a08cab3e21</UserSecretsId>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.3" />
		<PackageReference Include="Aspire.Hosting.Yarp" Version="13.3.3" />
		<PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" Version="13.0.0" />
		<PackageReference Include="Dapr.AspNetCore" Version="1.17.9" />
		<PackageReference Include="Dapr.Client" Version="1.17.9" />
		<PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" Version="13.3.3" />
		<PackageReference Include="Aspire.Hosting.SqlServer" Version="13.3.3" />
		<PackageReference Include="Aspire.Hosting.Azure.OperationalInsights" Version="13.3.3" />
		<PackageReference Include="Aspire.Hosting.Azure.Sql" Version="13.3.3" />
		<PackageReference Include="Aspire.Hosting.Redis" Version="13.3.3" />
		<PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.3.3" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.3" />
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.3.3" />
	</ItemGroup>
    <ItemGroup>
		<ProjectReference Include="..\MyApp.Audit\MyApp.Audit.API\MyApp.Audit.API.csproj" />
		<ProjectReference Include="..\MyApp.Auth\MyApp.Auth.API\MyApp.Auth.API.csproj" />
		<ProjectReference Include="..\MyApp.Sales\MyApp.Sales.API\MyApp.Sales.API.csproj" />
		<ProjectReference Include="..\MyApp.Billing\MyApp.Billing.API\MyApp.Billing.API.csproj" />
		<ProjectReference Include="..\MyApp.Inventory\MyApp.Inventory.API\MyApp.Inventory.API.csproj" />
		<ProjectReference Include="..\MyApp.Orders\MyApp.Orders.API\MyApp.Orders.API.csproj" />
		<ProjectReference Include="..\MyApp.Purchasing\MyApp.Purchasing.API\MyApp.Purchasing.API.csproj" />
		<ProjectReference Include="..\ErpApiGateway\ErpApiGateway.csproj" />
		<ProjectReference Include="..\MyApp.Shared\MyApp.Shared.Domain\MyApp.Shared.Domain.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\MyApp.Crm\MyApp.Crm.API\MyApp.Crm.API.csproj" />
		<ProjectReference Include="..\MyApp.Agentic\MyApp.Agentic.API\MyApp.Agentic.API.csproj" />
	</ItemGroup>
</Project>
