apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: myapp-apps
type: Opaque
stringData:
  jwt-secret-key: "replace-with-vault-synced-jwt-secret-key"
  otlp-api-key: "replace-with-128bits-entropy-key"
  otlp-header: "x-otlp-api-key=replace-with-128bits-entropy-key"
  redis-connection: "redis:6379,password=replace-with-vault-synced-redis-password,defaultDatabase=0,abortConnect=false,connectRetry=5,connectTimeout=5000,syncTimeout=5000"
  sql-connection-crmdb: "Server=sqlserver,1433;Database=CrmDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
  sql-connection-authdb: "Server=sqlserver,1433;Database=AuthDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
  sql-connection-billingdb: "Server=sqlserver,1433;Database=BillingDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
  sql-connection-inventorydb: "Server=sqlserver,1433;Database=InventoryDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
  sql-connection-ordersdb: "Server=sqlserver,1433;Database=OrdersDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
  sql-connection-purchasingdb: "Server=sqlserver,1433;Database=PurchasingDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
  sql-connection-salesdb: "Server=sqlserver,1433;Database=SalesDb;User Id=sqladmin;Password=replace-with-vault-synced-sa-or-sqladmin-password;TrustServerCertificate=True;Encrypt=False;ConnectRetryCount=10;ConnectRetryInterval=5;"
