apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-apps

resources:
  - auth-service.yaml
  - billing-service.yaml
  - crm-service.yaml
  - inventory-service.yaml
  - orders-service.yaml
  - purchasing-service.yaml
  - sales-service.yaml
  - gateway.yaml
  - aspire-dashboard.yaml

generatorOptions:
  disableNameSuffixHash: true
