apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../dev
  - letsencrypt-clusterissuers.yaml

patchesStrategicMerge:
  - patch-aspnetcore-environment.yaml
  - patch-gateway-ingress-letsencrypt.yaml
