### YamlMime:ManagedReference
items:
- uid: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto
  commentId: T:MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto
  id: CreateUpdateWarehouseDto
  parent: MyApp.Inventory.Application.Contracts.DTOs
  children:
  - MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location
  - MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name
  langs:
  - csharp
  - vb
  name: CreateUpdateWarehouseDto
  nameWithType: CreateUpdateWarehouseDto
  fullName: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto
  type: Class
  source:
    remote:
      path: src/MyApp.Inventory/MyApp.Inventory.Application.Contracts/DTOs/WarehouseDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: CreateUpdateWarehouseDto
    path: src/MyApp.Inventory/MyApp.Inventory.Application.Contracts/DTOs/WarehouseDtos.cs
    startLine: 11
  assemblies:
  - MyApp.Inventory.Application.Contracts
  namespace: MyApp.Inventory.Application.Contracts.DTOs
  syntax:
    content: public class CreateUpdateWarehouseDto
    content.vb: Public Class CreateUpdateWarehouseDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name
  commentId: P:MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name
  id: Name
  parent: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: CreateUpdateWarehouseDto.Name
  fullName: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name
  type: Property
  source:
    remote:
      path: src/MyApp.Inventory/MyApp.Inventory.Application.Contracts/DTOs/WarehouseDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Name
    path: src/MyApp.Inventory/MyApp.Inventory.Application.Contracts/DTOs/WarehouseDtos.cs
    startLine: 13
  assemblies:
  - MyApp.Inventory.Application.Contracts
  namespace: MyApp.Inventory.Application.Contracts.DTOs
  syntax:
    content: >-
      [Required(ErrorMessage = "Name is required")]

      [StringLength(255, MinimumLength = 1)]

      public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required(ErrorMessage:="Name is required")>

      <StringLength(255, MinimumLength:=1)>

      Public Property Name As String
  overload: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: Name is required
  - type: System.ComponentModel.DataAnnotations.StringLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.StringLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 255
    namedArguments:
    - name: MinimumLength
      type: System.Int32
      value: 1
- uid: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location
  commentId: P:MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location
  id: Location
  parent: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto
  langs:
  - csharp
  - vb
  name: Location
  nameWithType: CreateUpdateWarehouseDto.Location
  fullName: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location
  type: Property
  source:
    remote:
      path: src/MyApp.Inventory/MyApp.Inventory.Application.Contracts/DTOs/WarehouseDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Location
    path: src/MyApp.Inventory/MyApp.Inventory.Application.Contracts/DTOs/WarehouseDtos.cs
    startLine: 17
  assemblies:
  - MyApp.Inventory.Application.Contracts
  namespace: MyApp.Inventory.Application.Contracts.DTOs
  syntax:
    content: >-
      [Required(ErrorMessage = "Location is required")]

      [StringLength(500, MinimumLength = 1)]

      public string Location { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required(ErrorMessage:="Location is required")>

      <StringLength(500, MinimumLength:=1)>

      Public Property Location As String
  overload: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: Location is required
  - type: System.ComponentModel.DataAnnotations.StringLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.StringLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 500
    namedArguments:
    - name: MinimumLength
      type: System.Int32
      value: 1
references:
- uid: MyApp.Inventory.Application.Contracts.DTOs
  commentId: N:MyApp.Inventory.Application.Contracts.DTOs
  href: MyApp.html
  name: MyApp.Inventory.Application.Contracts.DTOs
  nameWithType: MyApp.Inventory.Application.Contracts.DTOs
  fullName: MyApp.Inventory.Application.Contracts.DTOs
  spec.csharp:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Inventory
    name: Inventory
    href: MyApp.Inventory.html
  - name: .
  - uid: MyApp.Inventory.Application
    name: Application
    href: MyApp.Inventory.Application.html
  - name: .
  - uid: MyApp.Inventory.Application.Contracts
    name: Contracts
    href: MyApp.Inventory.Application.Contracts.html
  - name: .
  - uid: MyApp.Inventory.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Inventory.Application.Contracts.DTOs.html
  spec.vb:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Inventory
    name: Inventory
    href: MyApp.Inventory.html
  - name: .
  - uid: MyApp.Inventory.Application
    name: Application
    href: MyApp.Inventory.Application.html
  - name: .
  - uid: MyApp.Inventory.Application.Contracts
    name: Contracts
    href: MyApp.Inventory.Application.Contracts.html
  - name: .
  - uid: MyApp.Inventory.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Inventory.Application.Contracts.DTOs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name*
  commentId: Overload:MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name
  href: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.html#MyApp_Inventory_Application_Contracts_DTOs_CreateUpdateWarehouseDto_Name
  name: Name
  nameWithType: CreateUpdateWarehouseDto.Name
  fullName: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location*
  commentId: Overload:MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location
  href: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.html#MyApp_Inventory_Application_Contracts_DTOs_CreateUpdateWarehouseDto_Location
  name: Location
  nameWithType: CreateUpdateWarehouseDto.Location
  fullName: MyApp.Inventory.Application.Contracts.DTOs.CreateUpdateWarehouseDto.Location
