### YamlMime:ManagedReference
items:
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto
  commentId: T:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto
  id: CreateUpdatePurchaseOrderLineDto
  parent: MyApp.Purchasing.Application.Contracts.DTOs
  children:
  - MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId
  - MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity
  - MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice
  langs:
  - csharp
  - vb
  name: CreateUpdatePurchaseOrderLineDto
  nameWithType: CreateUpdatePurchaseOrderLineDto
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto
  type: Class
  source:
    remote:
      path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: CreateUpdatePurchaseOrderLineDto
    path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
    startLine: 53
  assemblies:
  - MyApp.Purchasing.Application.Contracts
  namespace: MyApp.Purchasing.Application.Contracts.DTOs
  syntax:
    content: public class CreateUpdatePurchaseOrderLineDto
    content.vb: Public Class CreateUpdatePurchaseOrderLineDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId
  commentId: P:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId
  id: ProductId
  parent: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto
  langs:
  - csharp
  - vb
  name: ProductId
  nameWithType: CreateUpdatePurchaseOrderLineDto.ProductId
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId
  type: Property
  source:
    remote:
      path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: ProductId
    path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
    startLine: 55
  assemblies:
  - MyApp.Purchasing.Application.Contracts
  namespace: MyApp.Purchasing.Application.Contracts.DTOs
  syntax:
    content: >-
      [Required]

      public Guid ProductId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: >-
      <Required>

      Public Property ProductId As Guid
  overload: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity
  commentId: P:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity
  id: Quantity
  parent: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto
  langs:
  - csharp
  - vb
  name: Quantity
  nameWithType: CreateUpdatePurchaseOrderLineDto.Quantity
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity
  type: Property
  source:
    remote:
      path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Quantity
    path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
    startLine: 58
  assemblies:
  - MyApp.Purchasing.Application.Contracts
  namespace: MyApp.Purchasing.Application.Contracts.DTOs
  syntax:
    content: >-
      [Range(1, 2147483647, ErrorMessage = "Quantity must be at least 1")]

      public int Quantity { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Range(1, 2147483647, ErrorMessage:="Quantity must be at least 1")>

      Public Property Quantity As Integer
  overload: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RangeAttribute
    ctor: System.ComponentModel.DataAnnotations.RangeAttribute.#ctor(System.Int32,System.Int32)
    arguments:
    - type: System.Int32
      value: 1
    - type: System.Int32
      value: 2147483647
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: Quantity must be at least 1
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice
  commentId: P:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice
  id: UnitPrice
  parent: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto
  langs:
  - csharp
  - vb
  name: UnitPrice
  nameWithType: CreateUpdatePurchaseOrderLineDto.UnitPrice
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice
  type: Property
  source:
    remote:
      path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: UnitPrice
    path: src/MyApp.Purchasing/MyApp.Purchasing.Application.Contracts/DTOs/PurchaseOrderDtos.cs
    startLine: 61
  assemblies:
  - MyApp.Purchasing.Application.Contracts
  namespace: MyApp.Purchasing.Application.Contracts.DTOs
  syntax:
    content: >-
      [Range(0, 1.7976931348623157E+308, ErrorMessage = "UnitPrice must be greater than or equal to 0")]

      public decimal UnitPrice { get; set; }
    parameters: []
    return:
      type: System.Decimal
    content.vb: >-
      <Range(0, 1.7976931348623157E+308, ErrorMessage:="UnitPrice must be greater than or equal to 0")>

      Public Property UnitPrice As Decimal
  overload: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RangeAttribute
    ctor: System.ComponentModel.DataAnnotations.RangeAttribute.#ctor(System.Double,System.Double)
    arguments:
    - type: System.Double
      value: 0
    - type: System.Double
      value: 1.7976931348623157E+308
    namedArguments:
    - name: ErrorMessage
      type: System.String
      value: UnitPrice must be greater than or equal to 0
references:
- uid: MyApp.Purchasing.Application.Contracts.DTOs
  commentId: N:MyApp.Purchasing.Application.Contracts.DTOs
  href: MyApp.html
  name: MyApp.Purchasing.Application.Contracts.DTOs
  nameWithType: MyApp.Purchasing.Application.Contracts.DTOs
  fullName: MyApp.Purchasing.Application.Contracts.DTOs
  spec.csharp:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Purchasing
    name: Purchasing
    href: MyApp.Purchasing.html
  - name: .
  - uid: MyApp.Purchasing.Application
    name: Application
    href: MyApp.Purchasing.Application.html
  - name: .
  - uid: MyApp.Purchasing.Application.Contracts
    name: Contracts
    href: MyApp.Purchasing.Application.Contracts.html
  - name: .
  - uid: MyApp.Purchasing.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Purchasing.Application.Contracts.DTOs.html
  spec.vb:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Purchasing
    name: Purchasing
    href: MyApp.Purchasing.html
  - name: .
  - uid: MyApp.Purchasing.Application
    name: Application
    href: MyApp.Purchasing.Application.html
  - name: .
  - uid: MyApp.Purchasing.Application.Contracts
    name: Contracts
    href: MyApp.Purchasing.Application.Contracts.html
  - name: .
  - uid: MyApp.Purchasing.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Purchasing.Application.Contracts.DTOs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId*
  commentId: Overload:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId
  href: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.html#MyApp_Purchasing_Application_Contracts_DTOs_CreateUpdatePurchaseOrderLineDto_ProductId
  name: ProductId
  nameWithType: CreateUpdatePurchaseOrderLineDto.ProductId
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.ProductId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity*
  commentId: Overload:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity
  href: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.html#MyApp_Purchasing_Application_Contracts_DTOs_CreateUpdatePurchaseOrderLineDto_Quantity
  name: Quantity
  nameWithType: CreateUpdatePurchaseOrderLineDto.Quantity
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.Quantity
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice*
  commentId: Overload:MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice
  href: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.html#MyApp_Purchasing_Application_Contracts_DTOs_CreateUpdatePurchaseOrderLineDto_UnitPrice
  name: UnitPrice
  nameWithType: CreateUpdatePurchaseOrderLineDto.UnitPrice
  fullName: MyApp.Purchasing.Application.Contracts.DTOs.CreateUpdatePurchaseOrderLineDto.UnitPrice
- uid: System.Decimal
  commentId: T:System.Decimal
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.decimal
  name: decimal
  nameWithType: decimal
  fullName: decimal
  nameWithType.vb: Decimal
  fullName.vb: Decimal
  name.vb: Decimal
