### YamlMime:ManagedReference
items:
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  commentId: T:MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  id: PermissionDto
  parent: MyApp.Auth.Application.Contracts.DTOs
  children:
  - MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action
  - MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description
  - MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id
  - MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module
  langs:
  - csharp
  - vb
  name: PermissionDto
  nameWithType: PermissionDto
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  type: Class
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: PermissionDto
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
    startLine: 2
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public class PermissionDto
    content.vb: Public Class PermissionDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id
  id: Id
  parent: MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: PermissionDto.Id
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Id
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
    startLine: 4
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id*
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module
  id: Module
  parent: MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  langs:
  - csharp
  - vb
  name: Module
  nameWithType: PermissionDto.Module
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Module
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
    startLine: 5
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string Module { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property [Module] As String
  overload: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module*
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action
  id: Action
  parent: MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  langs:
  - csharp
  - vb
  name: Action
  nameWithType: PermissionDto.Action
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Action
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
    startLine: 6
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string Action { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Action As String
  overload: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action*
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description
  id: Description
  parent: MyApp.Auth.Application.Contracts.DTOs.PermissionDto
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: PermissionDto.Description
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Description
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/PermissionDto.cs
    startLine: 7
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string? Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description*
references:
- uid: MyApp.Auth.Application.Contracts.DTOs
  commentId: N:MyApp.Auth.Application.Contracts.DTOs
  href: MyApp.html
  name: MyApp.Auth.Application.Contracts.DTOs
  nameWithType: MyApp.Auth.Application.Contracts.DTOs
  fullName: MyApp.Auth.Application.Contracts.DTOs
  spec.csharp:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Auth
    name: Auth
    href: MyApp.Auth.html
  - name: .
  - uid: MyApp.Auth.Application
    name: Application
    href: MyApp.Auth.Application.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts
    name: Contracts
    href: MyApp.Auth.Application.Contracts.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Auth.Application.Contracts.DTOs.html
  spec.vb:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Auth
    name: Auth
    href: MyApp.Auth.html
  - name: .
  - uid: MyApp.Auth.Application
    name: Application
    href: MyApp.Auth.Application.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts
    name: Contracts
    href: MyApp.Auth.Application.Contracts.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Auth.Application.Contracts.DTOs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id
  href: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.html#MyApp_Auth_Application_Contracts_DTOs_PermissionDto_Id
  name: Id
  nameWithType: PermissionDto.Id
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module
  href: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.html#MyApp_Auth_Application_Contracts_DTOs_PermissionDto_Module
  name: Module
  nameWithType: PermissionDto.Module
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Module
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action
  href: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.html#MyApp_Auth_Application_Contracts_DTOs_PermissionDto_Action
  name: Action
  nameWithType: PermissionDto.Action
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Action
- uid: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description
  href: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.html#MyApp_Auth_Application_Contracts_DTOs_PermissionDto_Description
  name: Description
  nameWithType: PermissionDto.Description
  fullName: MyApp.Auth.Application.Contracts.DTOs.PermissionDto.Description
