### YamlMime:ManagedReference
items:
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  commentId: T:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  id: ExternalLoginDto
  parent: MyApp.Auth.Application.Contracts.DTOs
  children:
  - MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email
  - MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId
  - MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName
  - MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName
  - MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider
  langs:
  - csharp
  - vb
  name: ExternalLoginDto
  nameWithType: ExternalLoginDto
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  type: Class
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: ExternalLoginDto
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
    startLine: 2
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public class ExternalLoginDto
    content.vb: Public Class ExternalLoginDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider
  id: Provider
  parent: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  langs:
  - csharp
  - vb
  name: Provider
  nameWithType: ExternalLoginDto.Provider
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Provider
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
    startLine: 4
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string Provider { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Provider As String
  overload: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider*
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId
  id: ExternalId
  parent: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  langs:
  - csharp
  - vb
  name: ExternalId
  nameWithType: ExternalLoginDto.ExternalId
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: ExternalId
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
    startLine: 5
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string ExternalId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ExternalId As String
  overload: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId*
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email
  id: Email
  parent: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: ExternalLoginDto.Email
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: Email
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
    startLine: 6
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email*
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName
  id: FirstName
  parent: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  langs:
  - csharp
  - vb
  name: FirstName
  nameWithType: ExternalLoginDto.FirstName
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: FirstName
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
    startLine: 7
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string? FirstName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FirstName As String
  overload: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName*
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName
  commentId: P:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName
  id: LastName
  parent: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto
  langs:
  - csharp
  - vb
  name: LastName
  nameWithType: ExternalLoginDto.LastName
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName
  type: Property
  source:
    remote:
      path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
      branch: copilot/integrate-docfx-documentation
      repo: https://github.com/Ozymandros/ERP.Microservices.git
    id: LastName
    path: src/MyApp.Auth/MyApp.Auth.Application.Contracts/DTOs/ExternalLoginDto.cs
    startLine: 8
  assemblies:
  - MyApp.Auth.Application.Contracts
  namespace: MyApp.Auth.Application.Contracts.DTOs
  syntax:
    content: public string? LastName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LastName As String
  overload: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName*
references:
- uid: MyApp.Auth.Application.Contracts.DTOs
  commentId: N:MyApp.Auth.Application.Contracts.DTOs
  href: MyApp.html
  name: MyApp.Auth.Application.Contracts.DTOs
  nameWithType: MyApp.Auth.Application.Contracts.DTOs
  fullName: MyApp.Auth.Application.Contracts.DTOs
  spec.csharp:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Auth
    name: Auth
    href: MyApp.Auth.html
  - name: .
  - uid: MyApp.Auth.Application
    name: Application
    href: MyApp.Auth.Application.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts
    name: Contracts
    href: MyApp.Auth.Application.Contracts.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Auth.Application.Contracts.DTOs.html
  spec.vb:
  - uid: MyApp
    name: MyApp
    href: MyApp.html
  - name: .
  - uid: MyApp.Auth
    name: Auth
    href: MyApp.Auth.html
  - name: .
  - uid: MyApp.Auth.Application
    name: Application
    href: MyApp.Auth.Application.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts
    name: Contracts
    href: MyApp.Auth.Application.Contracts.html
  - name: .
  - uid: MyApp.Auth.Application.Contracts.DTOs
    name: DTOs
    href: MyApp.Auth.Application.Contracts.DTOs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider
  href: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.html#MyApp_Auth_Application_Contracts_DTOs_ExternalLoginDto_Provider
  name: Provider
  nameWithType: ExternalLoginDto.Provider
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Provider
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId
  href: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.html#MyApp_Auth_Application_Contracts_DTOs_ExternalLoginDto_ExternalId
  name: ExternalId
  nameWithType: ExternalLoginDto.ExternalId
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.ExternalId
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email
  href: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.html#MyApp_Auth_Application_Contracts_DTOs_ExternalLoginDto_Email
  name: Email
  nameWithType: ExternalLoginDto.Email
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.Email
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName
  href: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.html#MyApp_Auth_Application_Contracts_DTOs_ExternalLoginDto_FirstName
  name: FirstName
  nameWithType: ExternalLoginDto.FirstName
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.FirstName
- uid: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName*
  commentId: Overload:MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName
  href: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.html#MyApp_Auth_Application_Contracts_DTOs_ExternalLoginDto_LastName
  name: LastName
  nameWithType: ExternalLoginDto.LastName
  fullName: MyApp.Auth.Application.Contracts.DTOs.ExternalLoginDto.LastName
